name = "SeaTurtleID"
uuid = "d1cec66b-3ece-443d-aca3-c734a5a4f583"
authors = ["sergirovisu74@gmail.com"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.7"
